.travis.yml

Support #20656 Enable Travis on collection module

---

pom.xml
src/main/java/ca/gc/aafc/collection/api/MainConfiguration.java

21249 update dina base 45

---

README.md
local/collection-api.env
local/docker-compose.yml.example
local/pg.env

- Add collection-api.env, pg.env and docker-compose.yml.example files

Support 21302 Add docker compose.yml file

---

src/main/java/ca/gc/aafc/collection/api/repository/CollectingEventRepository.java
src/main/java/ca/gc/aafc/collection/api/service/CollectingEventService.java

Support-21363-Make-sure-dina-service-sets-uuid-for-collecting-event

---

pom.xml
src/test/java/ca/gc/aafc/collection/api/CollectionModuleStartupTest.java
src/test/java/ca/gc/aafc/collection/api/entities/CollectorGroupCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/repository/CollectingEventRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/repository/CollectorGroupRepositoryIT.java
src/test/resources/application-test.yml

Updated dina-base and SpringBoot

Support #21370 Update dependencies

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java

21400 bug when null imports

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectorGroupDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectorGroup.java
src/main/java/ca/gc/aafc/collection/api/repository/CollectorGroupRepository.java
src/test/java/ca/gc/aafc/collection/api/entities/CollectorGroupCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/repository/CollectorGroupRepositoryIT.java

- Change uuid-array to list-array in entity
- Add externalrelationshipprovider to repository
- Update tests

Support 21378 Change collector group to external relationships

---

local/collection-api.env
src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/4-Add_Group_to_collecting_event.xml
src/test/java/ca/gc/aafc/collection/api/repository/CollectingEventRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/factories/CollectingEventFactory.java

added group to collecting-event

21374 Add group to collecting-event

---

src/test/java/ca/gc/aafc/collection/api/openapi/CollectingEventOpenApiIT.java

set up open api test for collecting event

21382 integration test against api spec

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/test/java/ca/gc/aafc/collection/api/repository/CollectingEventRepositoryIT.java

quickly comment out the code causing issues for a hotfix

21603 bug in date filtering

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/10-Add_dwcRecordNumber_collecting_event.xml
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/CollectingEventOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/CollectingEventRepositoryIT.java

- Add into migration log, entity, dto
- Add CRUD and  repository tests

Support 21583-2 , Add field dwcRecordNumber to collecting-event

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/13-Update_dwcRecordNumber_collecting_event_table.xml
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/CollectingEventOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/CollectingEventRepositoryIT.java

- Update field to array type
- Update test

Support-21796-Change-dwcRecordNumber-to-an-array

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/15-Add_dwcOtherRecordNumbers_etc_collecting_event.xml
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/CollectingEventOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/CollectingEventRepositoryIT.java

- Update in migration log, entity and dto
- Update test

Support 21888 Add dwcOtherRecordNumbers

---

src/main/java/ca/gc/aafc/collection/api/dto/GeoreferenceAssertionDto.java
src/main/java/ca/gc/aafc/collection/api/entities/GeoreferenceAssertion.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/19-Add_dwcGeodeticDatum_georeference_assertion.xml

- Add to migration , entity and dto

Support 21942 Add dwcGeodeticDatum field to GeoreferenceAssertion

---

src/main/java/ca/gc/aafc/collection/api/entities/GeoreferenceAssertion.java

Add hibernate validation constraints

22015 Validate lat long geo reference

---

src/main/java/ca/gc/aafc/collection/api/dto/GeoreferenceAssertionDto.java

Update geo referenced by dto field to be an external relation.

22034 geo referenced by as external relation

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/23-Add_initial_place_fields_to_coll_event.xml
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java

- db migration
- entity and dto adjusted

22017 add initial place fields

---

src/main/java/ca/gc/aafc/collection/api/datetime/IsoDateTimeRsqlResolver.java
src/test/java/ca/gc/aafc/collection/api/repository/CollectingEventRepositoryIT.java

expand search operators  for start and end date

21596 expand search operators for start and end date

---

src/main/java/ca/gc/aafc/collection/api/entities/GeoreferenceAssertion.java

fix error  'georeferencedBy' can not be null.

22144 cant load existing geo assertion

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/java/ca/gc/aafc/collection/api/entities/GeographicPlaceNameSourceDetail.java
src/main/java/ca/gc/aafc/collection/api/service/CollectingEventService.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/27-Add_place_name_source_to_collecting_event.xml
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/repository/CollectingEventRepositoryIT.java

Example Post
```
"data": {
"type": "collecting-event",
"attributes": {
"createdBy": "fo",
"group":"dev",
"startEventDateTime": "1998",
"geographicPlaceNameSource":"OSM",
"geographicPlaceNameSourceDetail":{
"sourceID":"1",
"sourceIdType":"N",
"sourceUrl":"https://github.com/orgs/AAFC-BICoE/dashboard",
"date":" 2019-08-31T23:49:05.629+08:00"
}
}
}
}
```
Example response
```
...
"geographicPlaceNameSource": "OSM",
"geographicPlaceNameSourceDetail": {
"sourceID": "1",
"sourceIdType": "N",
"sourceUrl": "https://github.com/orgs/AAFC-BICoE/dashboard",
"date": "2019-08-31T15:49:05.629Z"
}
...
```

22132 add place name source to collecting event

---

pom.xml

Support #22191 Update dependencies

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/dto/GeoreferenceAssertionDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/java/ca/gc/aafc/collection/api/entities/GeoreferenceAssertion.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/28-Move_georeference_status_into_assertion.xml
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/GeoreferenceAssertionCRUDIT.java

https://redmine.biodiversity.agr.gc.ca/issues/22229

Move georeference status into assertion

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/31-Add_habitat_to_collecting_event.xml
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/repository/CollectingEventRepositoryIT.java

https://redmine.biodiversity.agr.gc.ca/issues/22399

22399 add field habitat to collecting-event

---

src/main/java/ca/gc/aafc/collection/api/dto/PreparationProcessDefinitionDto.java
src/main/java/ca/gc/aafc/collection/api/dto/PreparationProcessDto.java
src/main/java/ca/gc/aafc/collection/api/dto/PreparationProcessElementDto.java

https://redmine.biodiversity.agr.gc.ca/issues/22431

22431 Created Preparation Process Resources

---

src/main/java/ca/gc/aafc/collection/api/dto/PreparationProcessDto.java

https://redmine.biodiversity.agr.gc.ca/issues/22460

22460 preparation process resource date time should not be string

---

src/main/java/ca/gc/aafc/collection/api/dto/PreparationProcessDefinitionDto.java
src/main/java/ca/gc/aafc/collection/api/dto/PreparationProcessDto.java
src/main/java/ca/gc/aafc/collection/api/dto/PreparationProcessElementDto.java
src/main/java/ca/gc/aafc/collection/api/entities/PreparationProcess.java
src/main/java/ca/gc/aafc/collection/api/repository/PreparationProcessDefinitionRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/PreparationProcessDefinitonRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/PreparationProcessElementRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/PreparationProcessRepository.java
src/test/java/ca/gc/aafc/collection/api/repository/PreparationProcessDefinitionRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/repository/PreparationProcessElementRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/repository/PreparationProcessRepositoryIT.java

https://redmine.biodiversity.agr.gc.ca/issues/22477

22477 create repositories for prep process classes

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/38-Add_materialSampleName_to_MaterialSample.xml
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/repository/MaterialSampleRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/factories/MaterialSampleFactory.java

https://redmine.biodiversity.agr.gc.ca/issues/22514

22514 add material sample name to material sample

---

src/main/java/ca/gc/aafc/collection/api/entities/ManagedAttribute.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/40-Add_materialsample_to_managedattributecomponent.xml

Added MATERIAL_SAMPLE to ManagedAttributeComponent, added migration.

Feedback 22566

---

src/main/java/ca/gc/aafc/collection/api/dto/PreparationTypeDto.java
src/main/java/ca/gc/aafc/collection/api/entities/PreparationType.java
src/main/java/ca/gc/aafc/collection/api/repository/PreparationTypeRepository.java
src/main/java/ca/gc/aafc/collection/api/service/PreparationTypeService.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/41-Add_initial_PreparationType.xml
src/test/java/ca/gc/aafc/collection/api/entities/PreparationTypeCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/repository/PreparationTypeRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/factories/PreparationTypeFactory.java

https://redmine.biodiversity.agr.gc.ca/issues/22560

22560 add preparation type resource

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/java/ca/gc/aafc/collection/api/entities/PreparationType.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/42-Add_relationship_between_MaterialSample_And_PreparationType.xml
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java

https://redmine.biodiversity.agr.gc.ca/issues/22612

22612 add relationship between material sample and preparation type

---

src/main/java/ca/gc/aafc/collection/api/entities/GeographicPlaceNameSourceDetail.java
src/main/java/ca/gc/aafc/collection/api/validation/CollectingEventValidator.java
src/main/resources/validation-messages.properties
src/test/java/ca/gc/aafc/collection/api/validation/CollectingEventValidatorTest.java

https://redmine.biodiversity.agr.gc.ca/issues/22620

22620 add validation to geographic place name source detail

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/java/ca/gc/aafc/collection/api/service/MaterialSampleService.java
src/main/java/ca/gc/aafc/collection/api/validation/MaterialSampleValidator.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/43-Add_parent_MaterialSample_to_materialSample.xml
src/main/resources/validation-messages.properties
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java

https://redmine.biodiversity.agr.gc.ca/issues/22680

22680 add parent material sample to material sample

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectionDto.java
src/main/java/ca/gc/aafc/collection/api/entities/Collection.java
src/main/java/ca/gc/aafc/collection/api/repository/CollectionRepository.java
src/main/resources/db/changelog/migrations/44-Collection_code_max_size.xml
src/test/java/ca/gc/aafc/collection/api/repository/CollectionRepositoryIT.java

https://redmine.biodiversity.agr.gc.ca/issues/22750#change-126251

22750 expose collection endpoint

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/46-Add_otherCatalogNumbers_field_to_material_sample.xml
src/test/java/ca/gc/aafc/collection/api/entities/CollectionManagedAttributeCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/repository/MaterialSampleRepositoryIT.java

https://redmine.biodiversity.agr.gc.ca/issues/22789#change-126585

22789 Add otherCatalogNumbers field

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/48-add_prep_date_material_sample.xml
src/main/resources/db/changelog/migrations/49-add_prep_date_material_sample.xml
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/repository/MaterialSampleRepositoryIT.java

22832 add prep date mat sample

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java

Added patchStrategy to the managedAttributeValues field.

Feedback 22863

---

src/test/java/ca/gc/aafc/collection/api/CollectionModuleBaseIT.java
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/CollectionCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/CollectionManagedAttributeCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleActionDefinitionCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleActionRunCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/PreparationTypeCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/factories/CollectionFactory.java
src/test/java/ca/gc/aafc/collection/api/testsupport/factories/CollectionManagedAttributeFactory.java
src/test/java/ca/gc/aafc/collection/api/testsupport/factories/GeoreferenceAssertionFactory.java
src/test/java/ca/gc/aafc/collection/api/testsupport/factories/MaterialSampleActionDefinitionFactory.java

https://redmine.biodiversity.agr.gc.ca/issues/22917

22917 make complete use of test data provider

---

pom.xml
src/main/java/ca/gc/aafc/collection/api/service/CollectionManagedAttributeService.java

Updated dina-base and adjust class

22918 Update to dina-base 0.56

---

src/main/java/ca/gc/aafc/collection/api/entities/MaterialSampleActionDefinition.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/53-MatSampActionDef_Remove_group_unique.xml

22946 remove group unique mat samp action def

---

src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java

https://redmine.biodiversity.agr.gc.ca/issues/22798

22798 update material sample open api it to include all relations

---

src/test/java/ca/gc/aafc/collection/api/openapi/CollectionManagedAttributeOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleActionRunOpenApiIT.java

https://redmine.biodiversity.agr.gc.ca/issues/22802

22802 adjust api specs and testing pathing

---

pom.xml
src/main/java/ca/gc/aafc/collection/api/service/CollectingEventService.java
src/main/java/ca/gc/aafc/collection/api/service/CollectionManagedAttributeService.java
src/main/java/ca/gc/aafc/collection/api/service/CollectionService.java
src/main/java/ca/gc/aafc/collection/api/service/CollectorGroupService.java
src/main/java/ca/gc/aafc/collection/api/service/MaterialSampleActionDefinitionService.java
src/main/java/ca/gc/aafc/collection/api/service/MaterialSampleActionRunService.java
src/main/java/ca/gc/aafc/collection/api/service/MaterialSampleService.java
src/main/java/ca/gc/aafc/collection/api/service/MaterialSampleTypeService.java
src/main/java/ca/gc/aafc/collection/api/service/PreparationTypeService.java
src/test/java/ca/gc/aafc/collection/api/openapi/CollectingEventOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/CollectionManagedAttributeOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/CollectionOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleActionDefinitionOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleActionRunOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/PreparationTypeOpenApiIT.java

Fixed services and set strcitMode to false for remote schema validation

22970 Update to dina-base 0.57

---

src/test/java/ca/gc/aafc/collection/api/openapi/CollectingEventOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/CollectingEventRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/CollectingEventTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/22955

22955 create test fixture for collecting event

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/54-Add_MaterialSampleType_to_MaterialSample.xml
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java

https://redmine.biodiversity.agr.gc.ca/issues/22983

22983 add material sample type to material sample

---

src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/MaterialSampleRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/MaterialSampleTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/23013

23013 create test fixture for material sample

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/55-Add_structured_elevation_depth_fields.xml
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java

https://redmine.biodiversity.agr.gc.ca/issues/23054#change-127978

23054 add structured elevation depth fields

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java

https://redmine.biodiversity.agr.gc.ca/issues/23063

23063 structured elevation depth fields should not use primitive type s

---

src/test/java/ca/gc/aafc/collection/api/openapi/PreparationTypeOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/PreparationTypeRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/rest/PreparationTypeJsonApiIT.java
src/test/java/ca/gc/aafc/collection/api/rest/PreparationTypeJsonRestIT.java

https://redmine.biodiversity.agr.gc.ca/issues/23060

create test filtering on group, preparation type

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/dto/CollectorGroupDto.java
src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/external/ExternalResourceProviderImplementation.java
src/test/java/ca/gc/aafc/collection/api/openapi/CollectingEventOpenApiIT.java

Changed "agent" references to "person".

Feedback 23097

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/java/ca/gc/aafc/collection/api/service/MaterialSampleService.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/59-Add_managed_attribute_to_materialSample.xml
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java

https://redmine.biodiversity.agr.gc.ca/issues/23143

Add Managed attribute to material sample

---

src/main/resources/application.yml
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/initial-data/1-Create_MolecularSample_MaterialSampleType.xml

Added initial-data concept and entry for molecular extract

Support #23225 Create migration for molecular extract

---

pom.xml
src/test/java/ca/gc/aafc/collection/api/openapi/CollectingEventOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/CollectionManagedAttributeOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/CollectionOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleActionDefinitionOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleActionRunOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/PreparationTypeOpenApiIT.java

https://redmine.biodiversity.agr.gc.ca/issues/23254

23254 update to dina base 0.59

---

src/main/java/ca/gc/aafc/collection/api/repository/StorageUnitRepo.java
src/test/java/ca/gc/aafc/collection/api/rest/StorageUnitRestIT.java

hierarchy only shows in response when included in query spec of request

23285 enhance storage hierarchy

---

src/test/java/ca/gc/aafc/collection/api/openapi/CollectingEventOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleActionDefinitionOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/PreparationTypeOpenApiIT.java

https://redmine.biodiversity.agr.gc.ca/issues/23258

23258 update open api specs for missing properties

---

src/main/java/ca/gc/aafc/collection/api/dto/StorageUnitDto.java
src/main/java/ca/gc/aafc/collection/api/entities/StorageUnit.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/63-Add_link_from_storageUnit_to_storageType.xml
src/test/java/ca/gc/aafc/collection/api/rest/StorageUnitRestIT.java

https://redmine.biodiversity.agr.gc.ca/issues/23351

23351 add link from storage unit to storage type

---

src/main/resources/db/changelog/migrations/65-Remove_unique_index_on_storage_unit_table.xml

https://redmine.biodiversity.agr.gc.ca/issues/23378

23378 remove unique index on storage unit table

---

src/main/resources/db/changelog/db.changelog-master.xml

https://redmine.biodiversity.agr.gc.ca/issues/23393

23393 migration #65 is missing from the changelog

---

src/main/java/ca/gc/aafc/collection/api/repository/MaterialSampleRepository.java
src/test/java/ca/gc/aafc/collection/api/repository/MaterialSampleRepositoryIT.java

https://redmine.biodiversity.agr.gc.ca/issues/23402

23402 enable auditing on material sample repository

---

src/main/java/ca/gc/aafc/collection/api/service/StorageUnitService.java
src/main/java/ca/gc/aafc/collection/api/validation/StorageUnitValidator.java
src/main/resources/validation-messages.properties
src/test/java/ca/gc/aafc/collection/api/validation/StorageUnitValidatorTest.java

https://redmine.biodiversity.agr.gc.ca/issues/23448

23448 add storage unit validator

---

pom.xml

Support #23464 Update to dina-base 0.62

---

src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/67-PreparationType_name_should_be_unique_per_group.xml
src/test/java/ca/gc/aafc/collection/api/rest/PreparationTypeJsonRestIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/PreparationTypeTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/23468

23468 preparation type name should be unique per group

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/68-Add_preparationRemarks_field_to_MaterialSample.xml
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java

https://redmine.biodiversity.agr.gc.ca/issues/23478

23478 add preparation remarks field to material sample

---

src/main/java/ca/gc/aafc/collection/api/dto/StorageUnitDto.java
src/main/java/ca/gc/aafc/collection/api/entities/StorageUnit.java
src/main/java/ca/gc/aafc/collection/api/service/StorageHierarchicalObject.java
src/main/java/ca/gc/aafc/collection/api/service/StorageUnitService.java
src/test/java/ca/gc/aafc/collection/api/rest/StorageUnitRestIT.java

https://redmine.biodiversity.agr.gc.ca/issues/23446

23446 add type to storage unity hierarchy

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/69-Add_dwcDegreeOfEstablishment_to_MaterialSample.xml
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/CollectingEventOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/CollectionManagedAttributeOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/CollectionOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleActionDefinitionOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/PreparationTypeOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/MaterialSampleActionRunRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/repository/PreparationTypeRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/MaterialSampleTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/23492

23492 add dwc degree of establishment to material sample

---

src/test/resources/application-test.yml
src/test/resources/init-collection-module.sql

Use PostGIS image instead of Postgres and enabled postgis on collection schema

23531 Change Postgres image for Postgis

---

src/main/java/ca/gc/aafc/collection/api/VocabularyConfiguration.java
src/main/resources/vocabulary/coordinateSystem.yml
src/test/java/ca/gc/aafc/collection/api/repository/VocabularyRepositoryIT.java

https://redmine.biodiversity.agr.gc.ca/issues/23554

23554 move location coordinate sytem to vocabulary

---

src/main/java/ca/gc/aafc/collection/api/entities/GeographicPlaceNameSourceDetail.java

-Removed NotNull validation from the sourceUrl so the UI submissions can still be valid.

Feedback 23616

---

src/main/java/ca/gc/aafc/collection/api/entities/Determination.java
src/test/java/ca/gc/aafc/collection/api/repository/DeterminationIT.java

https://redmine.biodiversity.agr.gc.ca/issues/23551

23551 add field transcriber remarkers to determination

---

src/main/resources/vocabulary/doe.yml
src/test/java/ca/gc/aafc/collection/api/VocabularyConfigurationTest.java

https://redmine.biodiversity.agr.gc.ca/issues/23806

23806 complete doe vocabulary config file

---

pom.xml

Update dina-base and SpringBoot

23860 Update to dina-base 0.63

---

src/main/java/ca/gc/aafc/collection/api/entities/Determination.java
src/main/java/ca/gc/aafc/collection/api/validation/MaterialSampleValidator.java
src/main/resources/validation-messages.properties
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/validation/MaterialSampleValidatorTest.java

https://redmine.biodiversity.agr.gc.ca/issues/24138

24138 add validation on determination

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleActionRunOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java

https://redmine.biodiversity.agr.gc.ca/issues/24129

24129 set strict mode for open api tests

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/70-Add_host_fields.xml
src/test/java/ca/gc/aafc/collection/api/repository/CollectingEventRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/repository/MaterialSampleRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/CollectingEventTestFixture.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/MaterialSampleTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/24154

24154 add host fields

---

src/main/java/ca/gc/aafc/collection/api/VocabularyConfiguration.java
src/main/resources/vocabulary/substrate.yml
src/test/java/ca/gc/aafc/collection/api/repository/VocabularyRepositoryIT.java

https://redmine.biodiversity.agr.gc.ca/issues/24205

24205 create substrate vocabulary

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/java/ca/gc/aafc/collection/api/validation/CollectingEventValidator.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/71-Add_maxmimum_elevation_and_depth_fields.xml
src/main/resources/validation-messages.properties
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/CollectingEventTestFixture.java
src/test/java/ca/gc/aafc/collection/api/validation/CollectingEventValidatorTest.java

https://redmine.biodiversity.agr.gc.ca/issues/24201

24201 Add maximum elevation and depth fields

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/72-Add_substrate_to_collecting_event.xml
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/CollectingEventTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/24211

24211 add substrate to collecting event

---

src/main/java/ca/gc/aafc/collection/api/entities/Determination.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/DeterminationIT.java

https://redmine.biodiversity.agr.gc.ca/issues/24215

24215 rename determination verbatim agent

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectionDto.java

CollectionDto extends AttributeMetaInfoProvider

24251_collection_dto_as_meta_provider

---

src/test/java/ca/gc/aafc/collection/api/openapi/InstitutionOpenApiIT.java

https://redmine.biodiversity.agr.gc.ca/issues/24338

24338 create open api specs and test for institution resource

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/79-Revert_substrate_to_a_string.xml
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/CollectingEventTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/24353

24353 revert substrate to a string

---

src/main/java/ca/gc/aafc/collection/api/dto/InstitutionDto.java

InstitutionDto extends AttributeMetaInfoProvider

24352_institution_as_meta_info_provider

---

src/main/java/ca/gc/aafc/collection/api/entities/PreparationType.java
src/test/java/ca/gc/aafc/collection/api/testsupport/factories/PreparationTypeFactory.java

prep type extends UserDescribedDinaEntity

24366_prepType_extrend_described_entity

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/82-Add_Barcode_To_MatSample.xml
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/MaterialSampleRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/factories/MaterialSampleFactory.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/MaterialSampleTestFixture.java

24408_add_barcode_field_to_material_sample

24408_add_barcode_field_to_material_sample

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/java/ca/gc/aafc/collection/api/validation/CollectingEventValidator.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/83-Change_elevation_and_depth_fields_to_numeric.xml
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/CollectingEventTestFixture.java
src/test/java/ca/gc/aafc/collection/api/validation/CollectingEventValidatorTest.java

https://redmine.biodiversity.agr.gc.ca/issues/24445

24445 change elevation and depth fields to numeric

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/84-Add_tags_to_MaterialSample.xml
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/MaterialSampleTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/24490

24490 add tags to material sample

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/85-Add_publiclyReleasable.xml
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/CollectingEventTestFixture.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/MaterialSampleTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/24491

24491 add publicly releasable

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/87-Add_Material_Sample_State_and_Remarks_field.xml
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/MaterialSampleTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/24566

24566 add material sample state and remarks field

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/88-Add_tags_to_collectingEvent.xml
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/CollectingEventTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/24581

24581 add tags to collecting event

---

src/main/java/ca/gc/aafc/collection/api/MainConfiguration.java
src/main/java/ca/gc/aafc/collection/api/service/MaterialSampleService.java
src/main/resources/application.yml

material-sample service can now produce messages, a fallback is also provided

24500 Change MaterialSampleService to MessageProducingService

---

src/main/java/ca/gc/aafc/collection/api/dto/ImmutableMaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/AbstractMaterialSample.java
src/main/java/ca/gc/aafc/collection/api/entities/Organism.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/89-Add_organism_to_materialSample.xml
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java

https://redmine.biodiversity.agr.gc.ca/issues/24588

24588 add organism to material sample

---

src/main/java/ca/gc/aafc/collection/api/dto/InstitutionDto.java
src/main/java/ca/gc/aafc/collection/api/entities/Institution.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/91-Add_address_and_remarks_to_Institution.xml
src/test/java/ca/gc/aafc/collection/api/entities/InstitutionCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/InstitutionFixture.java

Create test for newlinehttps://redmine.biodiversity.agr.gc.ca/issues/24732

24732 add webpage, physicalAdress and remarks to institution

---

src/main/java/ca/gc/aafc/collection/api/dto/ImmutableMaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/AbstractMaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/92-Add_field_filedAs_to_MaterialSample.xml
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/MaterialSampleTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/24742

24742 add field filed as to material sample

---

src/main/java/ca/gc/aafc/collection/api/entities/Collection.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/92-Make_Collection_relationship_to_Institution_optional.xml

https://redmine.biodiversity.agr.gc.ca/issues/24743

24743 make collection relationship to institution optional

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectionDto.java
src/main/java/ca/gc/aafc/collection/api/entities/Collection.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/93-Add_fields_to_Collection.xml
src/test/java/ca/gc/aafc/collection/api/entities/CollectionCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/InstitutionCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/CollectionFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/24744

24744 add fields to collection

---

src/main/java/ca/gc/aafc/collection/api/dto/StorageUnitTypeDto.java
src/main/java/ca/gc/aafc/collection/api/entities/StorageUnitType.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/95-Add_isInseperable_to_StorageUnitType.xml
src/test/java/ca/gc/aafc/collection/api/openapi/StorageUnitTypeOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/StorageUnitTypeTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/24776

24776 add is inseperable to storage unit type

---

pom.xml

24783 Update to dina-base 0.68

---

src/main/java/ca/gc/aafc/collection/api/repository/MaterialSampleTypeRepository.java
src/test/java/ca/gc/aafc/collection/api/repository/MaterialSampleTypeRepositoryIT.java

https://redmine.biodiversity.agr.gc.ca/issues/24873

24873 change material sample type repository to use admin only authorization

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleTypeDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSampleType.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/96-MaterialSampleType_should_not_have_a_group.xml
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleTypeCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/repository/MaterialSampleTypeRepositoryIT.java

https://redmine.biodiversity.agr.gc.ca/issues/24889

24889 material sample type should not have a group

---

src/main/java/ca/gc/aafc/collection/api/dto/ImmutableMaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/AbstractMaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/97-Add_preparation_method_to_abstractMaterialSample.xml
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/MaterialSampleTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/24936

24936 add field preparationMethod to materialSample

---

pom.xml

https://redmine.biodiversity.agr.gc.ca/issues/25027

25027 update to dina base 0.70

---

src/main/resources/vocabulary/doe.yml
src/test/java/ca/gc/aafc/collection/api/VocabularyConfigurationTest.java

We are only keeping captive and cultivated

Support #25214 Remove content from doe.yml

---

src/main/java/ca/gc/aafc/collection/api/entities/AcquisitionEvent.java
src/main/java/ca/gc/aafc/collection/api/service/AcquisitionEventService.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/105-Add_acquisition_event.xml
src/test/java/ca/gc/aafc/collection/api/CollectionModuleBaseIT.java
src/test/java/ca/gc/aafc/collection/api/entities/AcquisitionEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/factories/AcquisitionEventFactory.java

https://redmine.biodiversity.agr.gc.ca/issues/25247

25247 add acquisition event

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectionDto.java
src/main/java/ca/gc/aafc/collection/api/entities/Collection.java
src/main/java/ca/gc/aafc/collection/api/service/CollectionService.java
src/main/java/ca/gc/aafc/collection/api/validation/CollectionValidator.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/105-Add_parentCollection_to_collection.xml
src/main/resources/validation-messages.properties
src/test/java/ca/gc/aafc/collection/api/openapi/CollectionOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/validation/CollectionValidatorTest.java
src/test/resources/application-test.yml

https://redmine.biodiversity.agr.gc.ca/issues/25228

25528 add parentCollection to collection

---

src/main/java/ca/gc/aafc/collection/api/dto/AcquisitionEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/AcquisitionEvent.java
src/main/java/ca/gc/aafc/collection/api/repository/AcquisitionEventRepository.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/107-Group_based_acquisition_event.xml
src/test/java/ca/gc/aafc/collection/api/entities/AcquisitionEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/AcquisitionEventOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/AcquisitionEventopenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/AcquisitionEventRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/repository/MaterialSampleRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/AcquisitionEventTestFixture.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/MaterialSampleTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/25269

25269 add acquisition event resource

---

src/main/java/ca/gc/aafc/collection/api/entities/Determination.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/DeterminationIT.java

Determination.java - scientificNameDetails converted to new class ScientificNameSourceDetails

25318_add_scientific_name_source_detail_to_determination

---

src/main/resources/vocabulary/associationType.yml

https://redmine.biodiversity.agr.gc.ca/issues/25310

25310 fix labels in association type file

---

src/main/java/ca/gc/aafc/collection/api/validation/AssociationValidator.java
src/main/resources/validation-messages.properties
src/test/java/ca/gc/aafc/collection/api/validation/AssociationValidatorTest.java

add validateAssociationNotSelf

25309_association_validator_validate_not_self

---

src/main/java/ca/gc/aafc/collection/api/repository/CollectionRepository.java
src/main/java/ca/gc/aafc/collection/api/security/CollectionAuthorizationService.java
src/main/java/ca/gc/aafc/collection/api/security/MinimumGroupAndRoleAuthorizationService.java
src/test/java/ca/gc/aafc/collection/api/repository/CollectionRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/repository/MaterialSampleRepositoryIT.java

https://redmine.biodiversity.agr.gc.ca/issues/25402

25402 change collection repository authorization service

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/AbstractMaterialSample.java
src/main/java/ca/gc/aafc/collection/api/entities/Determination.java
src/main/java/ca/gc/aafc/collection/api/validation/MaterialSampleValidator.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/108-Changed_filedAs_implementation.xml
src/main/resources/validation-messages.properties
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/validation/MaterialSampleValidatorTest.java

https://redmine.biodiversity.agr.gc.ca/issues/25306

25306 change filed as implementation

---

src/main/java/ca/gc/aafc/collection/api/entities/Determination.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/DeterminationIT.java

https://redmine.biodiversity.agr.gc.ca/issues/25448

25448 add missing remarks fields to determination

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/111-Add_MaterialSample_state_change_fields.xml
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/MaterialSampleTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/25459

25459 add material sample state change fields

---

src/main/java/ca/gc/aafc/collection/api/entities/MaterialSampleActionDefinition.java

Added ACQUISITION_EVENT to enum.

Feedback 25466

---

src/main/java/ca/gc/aafc/collection/api/service/MaterialSampleService.java
src/test/java/ca/gc/aafc/collection/api/service/MaterialSampleServiceIT.java

https://redmine.biodiversity.agr.gc.ca/issues/25482

Support #25482 - Inaccurate error reported on invalid association type

---

src/main/java/ca/gc/aafc/collection/api/entities/Project.java
src/main/java/ca/gc/aafc/collection/api/service/ProjectService.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/112-Add_Project_table.xml
src/test/java/ca/gc/aafc/collection/api/CollectionModuleBaseIT.java
src/test/java/ca/gc/aafc/collection/api/entities/ProjectCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/factories/ProjectFactory.java

https://redmine.biodiversity.agr.gc.ca/issues/25517

25517 create project entity and service

---

src/main/java/ca/gc/aafc/collection/api/service/CollectingEventService.java
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/CollectionCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/CollectionOpenApiIT.java

https://redmine.biodiversity.agr.gc.ca/issues/25506

25506 fix validators usage and testing

---

src/main/java/ca/gc/aafc/collection/api/dto/ProjectDto.java
src/main/java/ca/gc/aafc/collection/api/repository/ProjectRepository.java
src/main/java/ca/gc/aafc/collection/api/service/ProjectService.java
src/main/java/ca/gc/aafc/collection/api/validation/ProjectValidator.java
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/ProjectCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/AcquisitionEventOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/CollectingEventOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/ProjectOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/ProjectRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/rest/StorageUnitRestIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/ProjectTestFixture.java
src/test/java/ca/gc/aafc/collection/api/validation/ProjectValidatorTest.java

https://redmine.biodiversity.agr.gc.ca/issues/25522

25522 create project dto and repo

---

src/main/java/ca/gc/aafc/collection/api/dto/AcquisitionEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/AcquisitionEvent.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/113-Rename_external_fields_in_acquisition_event.xml
src/test/java/ca/gc/aafc/collection/api/entities/AcquisitionEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/AcquisitionEventOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/AcquisitionEventRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/AcquisitionEventTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/25535

25535 remove the word external from acquisition event

---

src/main/java/ca/gc/aafc/collection/api/service/StorageUnitService.java

https://redmine.biodiversity.agr.gc.ca/issues/25332

Support #25332 - Make StorageUnitService extending MessageProducingService

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/dto/ProjectDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/java/ca/gc/aafc/collection/api/entities/Project.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/114-Add_relationship_between_MaterialSample_and_Project.xml
src/test/java/ca/gc/aafc/collection/api/openapi/CollectingEventOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/CollectionOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleActionRunOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/ProjectOpenApiIT.java

https://redmine.biodiversity.agr.gc.ca/issues/25568

25568 add relationship between material sample and project

---

src/main/java/ca/gc/aafc/collection/api/entities/GeographicPlaceNameSourceDetail.java

https://redmine.biodiversity.agr.gc.ca/issues/25703

25703 Remove NotNull on stateProvince in GeographicPlaceNameSourceDetail

---

README.md

25711 Improve README with links to more documentation

---

src/main/java/ca/gc/aafc/collection/api/entities/Determination.java

https://redmine.biodiversity.agr.gc.ca/issues/25746

25746 add gna to scientific name source

---

src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleTypeOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/MaterialSampleTypeTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/25748

25748 material sample type missing from specs and material sample open api it

---

src/main/java/ca/gc/aafc/collection/api/entities/CollectionManagedAttribute.java
src/main/java/ca/gc/aafc/collection/api/service/CollectionManagedAttributeService.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/116-Add_DETERMINATION_to_ManagedAttributeComponent.xml
src/test/java/ca/gc/aafc/collection/api/service/CollectionManagedAttributeServiceIT.java

https://redmine.biodiversity.agr.gc.ca/issues/25747

25747 add determination to managed attribute component

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/java/ca/gc/aafc/collection/api/entities/ExtensionValue.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/116-Store_field_extension_values.xml
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/CollectingEventTestFixture.java

https://redmine.biodiversity.agr.gc.ca/issues/25728

25728 store field extension values

---

pom.xml
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/120-Update_jsonb_path_exists_varchar_function.xml
src/main/resources/log4j2.yaml

https://redmine.biodiversity.agr.gc.ca/issues/25825

25825 update to dina base 0.74

---

src/main/java/ca/gc/aafc/collection/api/dto/GeoreferenceAssertionDto.java
src/main/java/ca/gc/aafc/collection/api/dto/ScheduledActionDto.java
src/main/java/ca/gc/aafc/collection/api/entities/AbstractMaterialSample.java
src/main/java/ca/gc/aafc/collection/api/entities/AcquisitionEvent.java
src/main/java/ca/gc/aafc/collection/api/entities/Association.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/java/ca/gc/aafc/collection/api/entities/Collection.java
src/main/java/ca/gc/aafc/collection/api/entities/Determination.java
src/main/java/ca/gc/aafc/collection/api/entities/HostOrganism.java
src/main/java/ca/gc/aafc/collection/api/entities/Institution.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/java/ca/gc/aafc/collection/api/entities/Organism.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/121-Change_remarks_fields_to_TEXT.xml

https://redmine.biodiversity.agr.gc.ca/issues/25839

update all remarks db type to TEXT and set max size to 1000

---

src/main/java/ca/gc/aafc/collection/api/service/CollectingEventService.java
src/main/java/ca/gc/aafc/collection/api/validation/ExtensionValueValidator.java
src/main/resources/validation-messages.properties
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/CollectingEventTestFixture.java
src/test/java/ca/gc/aafc/collection/api/validation/ExtensionValueValidatorTest.java

https://redmine.biodiversity.agr.gc.ca/issues/25874

25874 add validator for extension value

---

pom.xml

updated dina-base and matching logj2

25948 Update to dina-base 0.75

---

pom.xml
src/main/java/ca/gc/aafc/collection/api/entities/Determination.java
src/main/java/ca/gc/aafc/collection/api/service/MaterialSampleService.java
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java

https://redmine.biodiversity.agr.gc.ca/issues/25965

25956 auto set is primary when there is only one determination

---

src/main/java/ca/gc/aafc/collection/api/entities/Determination.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/DeterminationIT.java

https://redmine.biodiversity.agr.gc.ca/issues/25976

25976 add classification path and classification ranks to scientific name source details

---

src/main/java/ca/gc/aafc/collection/api/entities/Determination.java
src/main/java/ca/gc/aafc/collection/api/service/MaterialSampleService.java
src/main/java/ca/gc/aafc/collection/api/validation/CollectionManagedAttributeValueValidator.java
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/factories/DeterminationFactory.java

https://redmine.biodiversity.agr.gc.ca/issues/25777

25777 add managed attributes to determination

---

src/main/java/ca/gc/aafc/collection/api/entities/Determination.java
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/repository/DeterminationIT.java

https://redmine.biodiversity.agr.gc.ca/issues/26025

26025 add current name and is synonym to scientific name source details

---

src/main/java/ca/gc/aafc/collection/api/service/MaterialSampleService.java
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java

https://redmine.biodiversity.agr.gc.ca/issues/26083

26083 create material sample with scientific name throws exception

---

pom.xml

https://redmine.biodiversity.agr.gc.ca/issues/26085

update to springboot 2.5.8

---

pom.xml
src/main/java/ca/gc/aafc/collection/api/service/MaterialSampleService.java
src/main/java/ca/gc/aafc/collection/api/service/StorageUnitService.java

Updated dina-base and adjust code related to MessageProducingService

26137 Update to dina-base 0.78

---

src/main/java/ca/gc/aafc/collection/api/dto/AssociationDto.java
src/main/java/ca/gc/aafc/collection/api/dto/CollectionDto.java
src/main/java/ca/gc/aafc/collection/api/dto/CollectionMethodDto.java
src/main/java/ca/gc/aafc/collection/api/dto/InstitutionDto.java
src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleActionDefinitionDto.java
src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleTypeDto.java
src/main/java/ca/gc/aafc/collection/api/dto/PreparationTypeDto.java
src/main/java/ca/gc/aafc/collection/api/dto/ProjectDto.java
src/main/java/ca/gc/aafc/collection/api/dto/ScheduledActionDto.java
src/main/java/ca/gc/aafc/collection/api/dto/StorageUnitDto.java
src/main/java/ca/gc/aafc/collection/api/dto/StorageUnitTypeDto.java
src/main/java/ca/gc/aafc/collection/api/entities/Determination.java
src/main/java/ca/gc/aafc/collection/api/entities/HostOrganism.java

-Added missing TypeName annotations.
-Added missing @Value annotations.

Feedback 26287

---

src/main/java/ca/gc/aafc/collection/api/entities/Association.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java

Feedback 26288

---

pom.xml
src/main/java/ca/gc/aafc/collection/api/repository/InstitutionRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/MaterialSampleTypeRepository.java
src/main/java/ca/gc/aafc/collection/api/security/CollectionAuthorizationService.java
src/main/java/ca/gc/aafc/collection/api/security/CollectionManagedAttributeAuthorizationService.java

Updated dina-base and related classes

Support #26319 Update to dina-base 0.80

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectionManagedAttributeDto.java
src/main/java/ca/gc/aafc/collection/api/dto/CollectionMethodDto.java
src/main/java/ca/gc/aafc/collection/api/dto/InstitutionDto.java
src/main/java/ca/gc/aafc/collection/api/dto/StorageUnitDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectionIdentifier.java
src/main/java/ca/gc/aafc/collection/api/entities/InstitutionIdentifier.java
src/main/java/ca/gc/aafc/collection/api/repository/AcquisitionEventRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/CollectionManagedAttributeRepo.java
src/main/java/ca/gc/aafc/collection/api/repository/CollectionMethodRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/CollectionRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/InstitutionRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/PreparationTypeRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/ProjectRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/StorageUnitRepo.java
src/main/java/ca/gc/aafc/collection/api/repository/StorageUnitTypeRepo.java

-Added @Value annotations to embedded data classes.
-Added missing @Id annotations.
-Added @DiffIgnore for computed values.
-Added auditing support to DInaRepository classes.

Feedback 26302

---

pom.xml

Updated dina-base, SpringBoot and related dependencies

26571 Update to dina-base 0.81

---

src/main/java/ca/gc/aafc/collection/api/service/OrganismService.java
src/test/java/ca/gc/aafc/collection/api/service/OrganismServiceIT.java

Added test for Determination where isPrimray is null
Fixed issue by checking for not true instead of isFalse

26625 Automatic set of primary determination is not working anymore

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/AbstractMaterialSample.java
src/main/java/ca/gc/aafc/collection/api/service/MaterialSampleService.java
src/main/java/ca/gc/aafc/collection/api/validation/MaterialSampleValidator.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/129-Add_restriction_boolean_and_remarks.xml
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/MaterialSampleTestFixture.java

Added remarks and boolean isRestricted that will be automagicaly set if there is a restriction.

26850 Add restriction remarks

---

pom.xml
src/main/java/ca/gc/aafc/collection/api/validation/CollectionManagedAttributeValueValidator.java
src/test/java/ca/gc/aafc/collection/api/entities/CollectionMethodCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/PreparationTypeCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/entities/ProjectCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/CollectionMethodTestFixture.java

Updated dina-base, SpringBoot and updated related code

27060 Update to dina-base 0.85

---

src/main/java/ca/gc/aafc/collection/api/repository/PreparationTypeRepository.java
src/test/java/ca/gc/aafc/collection/api/repository/PreparationTypeRepositoryIT.java

27329 Change preparation type to admin only

---

src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/131-Change_preparationType_Uniqueness_Constraint.xml
src/test/java/ca/gc/aafc/collection/api/entities/PreparationTypeCRUDIT.java

Replaced the old unique index on preparation-type

---

owasp-suppression.xml
pom.xml

Added dependency-check to build plugin section to allow the check in the CI pipeline

Added dependency-check to build plugin section

---

src/main/java/ca/gc/aafc/collection/api/dto/PreparationTypeDto.java
src/main/java/ca/gc/aafc/collection/api/dto/ProtocolDto.java

Add AttributeMetaInfoProvider to protocol and prep type

---

src/main/java/ca/gc/aafc/collection/api/dto/ImmutableMaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/AbstractMaterialSample.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java

Moved materialSampleType to abstract class so it can be returned in immutable versions

Add materialSampleType to abstract class

---

src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/137-Change_collectingevent_substrate_length.xml
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/CollectingEventTestFixture.java

27975 Fix substrate size

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/139-Rename_dwc_other_record_numbers.xml
src/test/java/ca/gc/aafc/collection/api/entities/CollectingEventCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/repository/CollectingEventRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/CollectingEventTestFixture.java

28056 Rename dwcOtherRecordNumbers to otherRecordNumbers

---

src/main/java/ca/gc/aafc/collection/api/entities/GridLayoutDefinition.java

Added more validation on numberOfRows and numberOfColumns

28074 Improve validation on GridLayoutDefinition

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/AbstractMaterialSample.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/145-Add_relationship_between_mat-sample_and_prep_method.xml
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/MaterialSampleTestFixture.java

Removed previous string-based PreparationMethod and replaced it by relationship

28143 Add relationship between mat-sample and prep method

---

src/main/resources/application.yml

28672 Change default security-constraints config

---

pom.xml
src/test/java/ca/gc/aafc/collection/api/repository/MaterialSampleRepositoryIT.java

Updated dina-base, SpringBoot. Added a test to prove the fix from dina-base is fixing the issue.

29337 Update dependencies

---

pom.xml

29774 Update to dina-base 0.101

---

src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/151-Add_managed_attribute_type_DECIMAL.xml
src/test/java/ca/gc/aafc/collection/api/entities/CollectionManagedAttributeCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/service/CollectionManagedAttributeServiceIT.java

Updated Postgres enum and added test coverage for all types

29826 Add decimal to managed attribute type pg enum

---

src/main/java/ca/gc/aafc/collection/api/repository/CollectingEventRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/MaterialSampleRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/OrganismRepository.java

Configured collecting-event, material-sample and organism repositories

29840 Allow acceptable text on collecting-event

---

pom.xml
src/main/java/ca/gc/aafc/collection/api/entities/Determination.java
src/main/java/ca/gc/aafc/collection/api/repository/CollectingEventRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/MaterialSampleRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/OrganismRepository.java

Updated dina-base, changed related code and increased verbatimDeterminer max size

29897 Update to dina-base 0.102

---

src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/154-Create_materialSampleType_cultureStrain.xml
src/main/resources/vocabulary/materialSampleType.yml
src/test/java/ca/gc/aafc/collection/api/service/MaterialSampleServiceIT.java

29936 Create material-sample type CultureStrain

---

src/main/java/ca/gc/aafc/collection/api/config/CollectionExtensionConfiguration.java
src/main/java/ca/gc/aafc/collection/api/config/CollectionVocabularyConfiguration.java
src/main/java/ca/gc/aafc/collection/api/dto/VocabularyDto.java
src/main/java/ca/gc/aafc/collection/api/repository/ExtensionRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/VocabularyRepository.java
src/main/java/ca/gc/aafc/collection/api/validation/AssociationValidator.java
src/main/java/ca/gc/aafc/collection/api/validation/BaseExtensionValueValidator.java
src/main/java/ca/gc/aafc/collection/api/validation/CollectingEventExtensionValueValidator.java
src/main/java/ca/gc/aafc/collection/api/validation/MaterialSampleExtensionValueValidator.java
src/main/java/ca/gc/aafc/collection/api/validation/RestrictionExtensionValueValidator.java
src/test/java/ca/gc/aafc/collection/api/ExtensionConfigurationTest.java
src/test/java/ca/gc/aafc/collection/api/VocabularyConfigurationTest.java
src/test/java/ca/gc/aafc/collection/api/repository/ExtensionRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/repository/VocabularyRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/validation/BaseExtensionValueValidatorTest.java

Added test for vocabulary protocolData, moved vocabulary based configuration class to config package.

29951 ProtocolData vocabulary not exposed

---

src/main/java/ca/gc/aafc/collection/api/config/CollectionExtensionConfiguration.java
src/test/java/ca/gc/aafc/collection/api/repository/ExtensionRepositoryIT.java

29989 mixsMicrobialv4 field extension file not loading in DINA

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/AbstractMaterialSample.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectionManagedAttribute.java
src/main/java/ca/gc/aafc/collection/api/service/MaterialSampleService.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/155-Add_preparation_managed_attribute.xml
src/test/java/ca/gc/aafc/collection/api/entities/MaterialSampleCRUDIT.java
src/test/java/ca/gc/aafc/collection/api/service/MaterialSampleServiceIT.java

Added preparation component and moved the managed attribute IT tests to service

30172 Add preparation component managed attribute

---

pom.xml

Updated SpringBoot and dina-base

30495 Release collection-api 0.74

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java
src/main/java/ca/gc/aafc/collection/api/entities/CollectingEvent.java
src/main/java/ca/gc/aafc/collection/api/entities/PreparationType.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/157-Add_protocol_to_collecting-event.xml
src/test/java/ca/gc/aafc/collection/api/openapi/CollectingEventOpenApiIT.java
src/test/java/ca/gc/aafc/collection/api/openapi/MaterialSampleOpenApiIT.java

30610 Add protocol to collecting-event

---

pom.xml
src/main/java/ca/gc/aafc/collection/api/repository/AcquisitionEventRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/AssemblageRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/CollectingEventRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/CollectionSequenceGeneratorRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/FormTemplateRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/InstitutionRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/MaterialSampleRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/OrganismRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/ProjectRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/StorageUnitRepo.java
src/main/java/ca/gc/aafc/collection/api/repository/StorageUnitTypeRepo.java
src/main/java/ca/gc/aafc/collection/api/security/SuperUserInGroupCUDAuthorizationService.java
src/test/java/ca/gc/aafc/collection/api/repository/MaterialSampleRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/rest/StorageUnitRestIT.java

Updated dina-base and related code + fix tests

30626 Update to dina-base 0.104

---

src/main/java/ca/gc/aafc/collection/api/repository/FormTemplateRepository.java
src/test/java/ca/gc/aafc/collection/api/repository/FormTemplateRepositoryIT.java

Now using ObjectOwnerAuthorizationService + added test

30309 Change form-template authorization

---

src/test/java/ca/gc/aafc/collection/api/openapi/StorageUnitOpenApiIT.java

Tests pass with new schema changes

29912: StorageUnit_test

---

src/main/java/ca/gc/aafc/collection/api/entities/UserDescribedDinaEntity.java

31053 Add valid annotation to MultilingualDescription attributes

---

pom.xml
src/main/java/ca/gc/aafc/collection/api/service/CollectingEventService.java

Enabled message producing for collecting-event UPDATE and DELETE

31223 Change collecting-event service to message producer

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectingEventDto.java

31674 Replace Nullable annotation

---

src/main/java/ca/gc/aafc/collection/api/dto/CollectionManagedAttributeDto.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/CollectionManagedAttributeTestFixture.java

Added unit field to dto + updated test

31134 Expose unit in managed attribute dto

---

pom.xml
src/test/resources/application-test.yml

Updated dina-base + fix dev-user config

32063 Update dependencies

---

src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/162-Increase_name_size_controlled_vocabulary.xml

Field sizes needed by the Uebersee Museum.

Increase name size for collection-method, preparation_method and preparation_type

---

src/main/java/ca/gc/aafc/collection/api/config/CollectionVocabularyConfiguration.java
src/main/resources/vocabulary/taxonomicRank.yml
src/test/java/ca/gc/aafc/collection/api/repository/VocabularyRepositoryIT.java

Added vocabulary for taxonomic ranks

32970 Add Controlled Vocabulary for taxonomic rank

---

src/main/java/ca/gc/aafc/collection/api/dto/MaterialSampleDto.java
src/main/java/ca/gc/aafc/collection/api/entities/MaterialSample.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/163-Add_source_set_to_material_sample.xml

33087 Add a source_set field to material-sample

---

src/main/java/ca/gc/aafc/collection/api/repository/ResourceNameIdentifierRepository.java

Added configuration for assemblage

33643 Implement resource-id for assemblage

---

src/main/java/ca/gc/aafc/collection/api/entities/StorageUnitCoordinates.java
src/test/java/ca/gc/aafc/collection/api/repository/StorageUnitCoordinatesRepositoryIT.java

Added validation for empty row/col

34069 StorageUnitCoordinates should not accept empty coordinates

---

src/main/java/ca/gc/aafc/collection/api/dto/StorageUnitCoordinatesDto.java
src/main/java/ca/gc/aafc/collection/api/entities/StorageUnitCoordinates.java
src/main/java/ca/gc/aafc/collection/api/service/StorageUnitCoordinatesService.java
src/main/java/ca/gc/aafc/collection/api/validation/StorageUnitCoordinatesValidator.java
src/test/java/ca/gc/aafc/collection/api/repository/StorageUnitCoordinatesRepositoryIT.java

Added calculated cellNumber to StorageUnitCoordinates

34121 Add cellNumber StorageUnitCoordinates

---

pom.xml
src/main/java/ca/gc/aafc/collection/api/service/VocabularyService.java

Use CollectionBackedReadOnlyDinaService for vocabulary service

34169 Update to dina-base 0.127

---

src/main/resources/extension/NCBI_SRA_Projectv1.yml
src/main/resources/extension/NcbiSraProjectV1.yml

Addition of the NCBI SRA Peoject Field Extension for DINA

NCBI Project Field Extension Information

---

src/main/java/ca/gc/aafc/collection/api/repository/ResourceNameIdentifierRepository.java
src/main/java/ca/gc/aafc/collection/api/repository/VocabularyRepositoryV2.java

Added handling of null query string

34976 Issues with empty query params in readonly v2 endpoints

---

src/main/java/ca/gc/aafc/collection/api/entities/StorageUnitUsage.java
src/test/java/ca/gc/aafc/collection/api/repository/StorageUnitUsageRepositoryIT.java

35136 Issue with StorageUnitUsage regex on wellRow

---

src/main/resources/vocabulary/protocolVocabulary.yml

35226 Create new protocol type for Generic Molecular Analysis

---

src/main/java/ca/gc/aafc/collection/api/dto/OrganismDto.java
src/main/java/ca/gc/aafc/collection/api/entities/Organism.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/175-Add_vernacularName_to_organism.xml
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/OrganismTestFixture.java

35418 Add vernacularName to organism

---

src/main/java/ca/gc/aafc/collection/api/config/CollectionVocabularyConfiguration.java
src/main/java/ca/gc/aafc/collection/api/dto/ProjectDto.java
src/main/java/ca/gc/aafc/collection/api/entities/Project.java
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/migrations/176-Add_contributors_to_project.xml
src/main/resources/vocabulary/projectRole.yml
src/test/java/ca/gc/aafc/collection/api/repository/IndexRefreshRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/repository/VocabularyRepositoryIT.java
src/test/java/ca/gc/aafc/collection/api/testsupport/fixtures/ProjectTestFixture.java

Added fields + vocabulary. No validation for the moment.

35462 Add contributors to project

---

pom.xml
src/test/java/ca/gc/aafc/collection/api/repository/InstitutionRepositoryIT.java

Updated dina-base and fixed related test

35747 Update dina-base to 0.137

---

src/main/resources/extension/agronomy_ontology.yml
src/main/resources/extension/mixsSoilv4.yml
src/main/resources/extension/mixsWaterv4.yml

Added missing vocabularyElementType

36024 Force type of field extension that are not text

---

src/main/resources/extension/mixsSoilv4.yml
src/main/resources/extension/mixsWaterv4.yml

Made changes to mixSWaterv4.yml and mixsSoilv4.yml for relevant fields

Support 36028 force grdi field extension types that are not text
